---
sensors:
    - name : garageDoor
      pin : 21
      type : door
      category: gpio
    - name : mudRoomDoor
      pin : 22
      type : door
      category: gpio
    - name : frontDoor
      pin : 23
      type : door
      category: gpio
    - name : sliderDoor
      pin : 24
      type : door
      category: gpio
    - name : basementDoor
      pin : 5
      type : door
      category: gpio
brokers :
    - name : hass
      protocol : mqtt
      type : blocking
      address : 192.168.4.10
      port : 1883
      ca_certs : /etc/home/ssl/fullchain.pem
      key_file : /etc/home/ssl/privkey.pem
      cert_file : /etc/home/ssl/fullchain.pem
